#!/bin/bash

TIMEFORMAT='TOTAL TIME (USER)=%3lU'

date +"===================> %c <==================="

echo '===================> PROCESSING...'
time ./process.sh $1 $2 $3 $6 0 $5 $7 $4

date +"===================> %c <==================="
