#!/bin/bash

# Output dirs.
export DIR_HASH=.
export DIR_HASH_XZ=/spacio/azrael

make clean
make all
make test
#./run-sample $DIR_HASH $DIR_HASH_XZ ../../rockyou.txt out64-rock.hash 64 1
#./run-sample $DIR_HASH $DIR_HASH_XZ ../../rockyou.txt out320-rock.hash 320 1
#./run-sample $DIR_HASH $DIR_HASH_XZ ../../rockyou.txt out512-rock.hash 512 1
./run-sample $DIR_HASH $DIR_HASH_XZ ../../rockyou.txt outx4-rock.hash x4 1
#./run-sample $DIR_HASH $DIR_HASH_XZ ../../rockyou.txt outxM-rock.hash xM 1
#./run-sample $DIR_HASH $DIR_HASH_XZ ../../rockyou.txt outxMM-rock.hash xMM 1